# Generated by Django 5.2 on 2025-05-02 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Student Name')),
                ('studentId', models.PositiveBigIntegerField(unique=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('department', models.CharField(max_length=120)),
                ('course', models.CharField(max_length=120)),
                ('campus', models.CharField(max_length=100)),
                ('qrId', models.CharField(max_length=100, unique=True)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='User')),
                ('email', models.EmailField(max_length=254, verbose_name='User email')),
                ('windowNum', models.PositiveSmallIntegerField(verbose_name='Window Number')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queueNumber', models.CharField(max_length=10)),
                ('transactionType', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('priority', models.BooleanField(default=False)),
                ('onHoldCount', models.PositiveSmallIntegerField(default=0)),
                ('requestedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.student')),
                ('reservedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
    ]
