# Generated by Django 5.2 on 2025-05-02 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roles', models.CharField(default='Guest', max_length=10, verbose_name='Role')),
                ('department', models.CharField(max_length=120)),
                ('qrId', models.CharField(max_length=100, unique=True)),
                ('priority', models.BooleanField(default=False)),
                ('campus', models.CharField(default='SOUTH', max_length=100)),
                ('course', models.CharField(max_length=120)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewEnrollee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roles', models.CharField(default='New Enroll', max_length=10, verbose_name='Role')),
                ('department', models.CharField(default='CAS', max_length=120)),
                ('qrId', models.CharField(max_length=100, unique=True)),
                ('priority', models.BooleanField(default=False)),
                ('campus', models.CharField(default='SOUTH', max_length=100)),
                ('course', models.CharField(max_length=120)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='requestedBy',
        ),
        migrations.AddField(
            model_name='student',
            name='roles',
            field=models.CharField(default='student', max_length=10, verbose_name='Role'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='requester_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='requester_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='user',
            name='process_mode',
            field=models.CharField(choices=[('mixed', 'Mixed'), ('priority_only', 'Priority Only'), ('standard_only', 'Standard Only')], default='mixed', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('on_queue', 'On Queue'), ('in_process', 'In Process'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='on_queue', max_length=50),
        ),
    ]
