# Generated by Django 5.2 on 2025-05-02 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_guest_newenrollee_remove_transaction_requestedby_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verifyied',
            field=models.BooleanField(default=False),
        ),
    ]
