# Generated by Django 5.2 on 2025-05-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_verifyied'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='verifyied',
            new_name='verified',
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$K5UKnq35v8KL8B3sQOAhxe$O5+lypTL6uRRSg8BGyeojk/XB5210rrcDr+P0Lmn0A4=', max_length=128, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='User email'),
        ),
    ]
