# Generated by Django 5.2 on 2025-05-02 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_verifyied_user_verified_user_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$NJJ4ssNzUGfERXf5xadjC7$q1ocBlyX+LQ6xUtK1dYMQZ/ghWYl13pkAeMjdqKoLA0=', max_length=128, verbose_name='Password'),
        ),
    ]
