# Generated by Django 5.2 on 2025-05-02 20:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$cwwekokXRgZK418WjwXF4j$ZGxwa8JCXpOcqFn5eNh3gS+rIcc2BhwAMuA+pj4Q2jk=', max_length=128, verbose_name='Password'),
        ),
    ]
