# Generated by Django 5.2 on 2025-05-02 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_transaction_created_at_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$pNLYY9QVyc0mAYcYfH5GEV$wyaSuHDR+ui2GU2FSoR6JjiUv9xitRi2h9D63Zj7LKs=', max_length=128, verbose_name='Password'),
        ),
    ]
