# Generated by Django 5.2 on 2025-05-03 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$mNrqT3vXdflxjO6sT9PG4B$tyxPIZrKvrquer2TkWaG2SXWmrkVlGviVvhDR0bog0I=', max_length=128, verbose_name='Password'),
        ),
    ]
