# Generated by Django 5.2 on 2025-05-03 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('on_queue', 'On Queue'), ('in_process', 'In Process'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('on_hold', 'On Hold')], default='on_queue', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$rUoUucQx53vRBtgjfFsG91$dpXmFMKUk/hitUZK0RSVG7EfSLeYlcIitxQudczhWCw=', max_length=128, verbose_name='Password'),
        ),
    ]
