# Generated by Django 5.2 on 2025-05-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_transaction_status_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isAdmin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$u1ghd1Yl0AHVvWcLlpSrpm$/2usqeOjNlBvfJPmbbzpkpVolIWA0K7DVJ5qwnN55zc=', max_length=128, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='windowNum',
            field=models.PositiveSmallIntegerField(unique=True, verbose_name='Window Number'),
        ),
    ]
