# Generated by Django 5.2 on 2025-05-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_user_isadmin_alter_user_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isOnline',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$2ZgrMGYUIBEVM1lzJOC3rb$BpjS5DMMMifZr9FNoi2WtCzA6/vp4sRWz2V1yMd3yso=', max_length=128, verbose_name='Password'),
        ),
    ]
