# Generated by Django 5.2 on 2025-05-04 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_newenrollee_campus_alter_student_campus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$s62EWdyJj3Vb31KGL0sTj8$EFqgcoNAb6O3tgx+hMAmnvDSJsuMqxU66rTbpJ1SHI4=', max_length=128, verbose_name='Password'),
        ),
    ]
