# Generated by Django 5.2 on 2025-05-04 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$LZxK67SU9uXFFFY1z0NraJ$GfDnygFRreRyZujopspoRYqrucV/gTjY5emtMKtrPdE=', max_length=128, verbose_name='Password'),
        ),
    ]
