# Generated by Django 5.2 on 2025-05-04 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_transaction_created_at_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$oKjSGlMW3jt7ZCtzxUH2ho$DsgIeD/pcZUSelKCD+Rfvdlr4+iomQ9po+eQvuv45QQ=', max_length=128, verbose_name='Password'),
        ),
        migrations.CreateModel(
            name='TransactionNF1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queueNumber', models.CharField(db_index=True, max_length=10, unique=True)),
                ('transactionType', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('on_queue', 'On Queue'), ('in_process', 'In Process'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('on_hold', 'On Hold'), ('cut_off', 'Cut Off')], db_index=True, default='on_queue', max_length=50)),
                ('priority', models.BooleanField(default=False)),
                ('onHoldCount', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.CharField(choices=[('Engineering', 'Engineering'), ('Information and Computing Sciences', 'Information and Computing Sciences'), ('Business and Accountancy', 'Business and Accountancy'), ('Arts and Sciences', 'Arts and Sciences'), ('Education', 'Education'), ('Nursing', 'Nursing'), ('Architecture and Fine Arts', 'Architecture and Fine Arts'), ('Agriculture and Forestry', 'Agriculture and Forestry'), ('Law', 'Law'), ('Medicine', 'Medicine'), ('Health Sciences', 'Health Sciences'), ('Hospitality and Tourism Management', 'Hospitality and Tourism Management'), ('Criminal Justice Education', 'Criminal Justice Education'), ('Social Work and Community Development', 'Social Work and Community Development')], max_length=120)),
                ('course', models.CharField(choices=[('BS Civil Engineering', 'BS Civil Engineering'), ('BS Mechanical Engineering', 'BS Mechanical Engineering'), ('BS Electrical Engineering', 'BS Electrical Engineering'), ('BS Electronics and Communications Engineering', 'BS Electronics and Communications Engineering'), ('BS Chemical Engineering', 'BS Chemical Engineering'), ('BS Computer Science', 'BS Computer Science'), ('BS Information Technology', 'BS Information Technology'), ('BS Information Systems', 'BS Information Systems'), ('BS Software Engineering', 'BS Software Engineering'), ('BS Business Administration (Major in Marketing Management)', 'BS Business Administration (Marketing Management)'), ('BS Business Administration (Major in Financial Management)', 'BS Business Administration (Financial Management)'), ('BS Accountancy', 'BS Accountancy'), ('BS Entrepreneurship', 'BS Entrepreneurship'), ('BS Management Accounting', 'BS Management Accounting'), ('AB Psychology', 'AB Psychology'), ('AB Political Science', 'AB Political Science'), ('AB English Studies', 'AB English Studies'), ('AB History', 'AB History'), ('BS Biology', 'BS Biology'), ('BS Chemistry', 'BS Chemistry'), ('BS Mathematics', 'BS Mathematics'), ('BSEd English', 'BSEd English'), ('BSEd Mathematics', 'BSEd Mathematics'), ('BSEd Science', 'BSEd Science'), ('BS Early Childhood Education', 'BS Early Childhood Education'), ('BS Nursing', 'BS Nursing'), ('BS Architecture', 'BS Architecture'), ('BS Interior Design', 'BS Interior Design'), ('BS Fine Arts (major in Painting, Sculpture, or Multimedia Arts)', 'BS Fine Arts'), ('BS Agriculture', 'BS Agriculture'), ('BS Agricultural Engineering', 'BS Agricultural Engineering'), ('BS Forestry', 'BS Forestry'), ('Bachelor of Laws (LLB)', 'Bachelor of Laws (LLB)'), ('Juris Doctor (JD)', 'Juris Doctor (JD)'), ('Doctor of Medicine (MD)', 'Doctor of Medicine (MD)'), ('BS Medical Technology', 'BS Medical Technology'), ('BS Radiologic Technology', 'BS Radiologic Technology'), ('BS Physical Therapy', 'BS Physical Therapy'), ('BS Occupational Therapy', 'BS Occupational Therapy'), ('BS Hospitality Management', 'BS Hospitality Management'), ('BS Tourism Management', 'BS Tourism Management'), ('BS Criminology', 'BS Criminology'), ('BS Social Work', 'BS Social Work')], max_length=120)),
                ('campus', models.CharField(choices=[('Main', 'Main'), ('South', 'South'), ('San Jose', 'San Jose')], max_length=100)),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.guest')),
                ('new_enrollee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.newenrollee')),
                ('reservedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reserved_transactions', to='core.user')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.student')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('queueNumber',), name='unique_queue_number')],
            },
        ),
    ]
