# Generated by Django 5.2 on 2025-05-04 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_user_password_transactionnf1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$969FHfvvgEKicZXZi18OO2$zQYxmZI99LTe3TmwXb6ua8Ae1zHv5as6QFGnZbddkzU=', max_length=128, verbose_name='Password'),
        ),
    ]
