# Generated by Django 5.2 on 2025-05-04 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$xKsmfejKd6ZzNRxHExZhGU$53MQCWz8Xb7ZFJXDe7tmhFs1N7enkO1js5JGXG8wrXs=', max_length=128, verbose_name='Password'),
        ),
    ]
