# Generated by Django 5.2 on 2025-05-04 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$Yp5kDLBIHYfgkqdEeVUB5A$jsc9UyDUzOAswV7Ox/B/q2h5s3S5ZSpI9M5g8vKr3nI=', max_length=128, verbose_name='Password'),
        ),
    ]
