# Generated by Django 5.2 on 2025-05-04 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$AK2xE0WAlQL8Z3l1Q1xKrB$uKIFw4vGapLdKqUlkTQJK25p3+vlNH0KYouoqqlbc5o=', max_length=128, verbose_name='Password'),
        ),
    ]
