# Generated by Django 5.2 on 2025-05-04 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$4sJW2slBQJDCw34nP4pcql$0rohgF0Kd9HxjUTEzxqBxy5+t6USxHVBUe8ijb8vcek=', max_length=128, verbose_name='Password'),
        ),
    ]
