# Generated by Django 5.2 on 2025-05-04 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$T5aWcpQJJCmdzKKtwuCORK$GgmwiFJy/xk/LcJYMwZfQiVYvXV3PNxFtwieeeOEmX4=', max_length=128, verbose_name='Password'),
        ),
    ]
