# Generated by Django 5.2 on 2025-05-05 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueState',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('position', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$zkKXII1ufxKKLuCHz0EV4E$xhheUeZvVux6Lo3yhndlVYf4xyMz/gYRHSRUVoCHKCA=', max_length=128, verbose_name='Password'),
        ),
    ]
