# Generated by Django 5.2 on 2025-05-05 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_department_alter_user_password_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='requester_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='requester_type',
        ),
        migrations.AddField(
            model_name='transaction',
            name='guest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legacy_transactions', to='core.guest'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='new_enrollee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legacy_transactions', to='core.newenrollee'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legacy_transactions', to='core.student'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='course',
            field=models.CharField(choices=[('BS Civil Engineering', 'BS Civil Engineering'), ('BS Mechanical Engineering', 'BS Mechanical Engineering'), ('BS Electrical Engineering', 'BS Electrical Engineering'), ('BS Electronics and Communications Engineering', 'BS Electronics and Communications Engineering'), ('BS Chemical Engineering', 'BS Chemical Engineering'), ('BS Computer Science', 'BS Computer Science'), ('BS Information Technology', 'BS Information Technology'), ('BS Information Systems', 'BS Information Systems'), ('BS Software Engineering', 'BS Software Engineering'), ('BS Business Administration (Major in Marketing Management)', 'BS Business Administration (Marketing Management)'), ('BS Business Administration (Major in Financial Management)', 'BS Business Administration (Financial Management)'), ('BS Accountancy', 'BS Accountancy'), ('BS Entrepreneurship', 'BS Entrepreneurship'), ('BS Management Accounting', 'BS Management Accounting'), ('AB Psychology', 'AB Psychology'), ('AB Political Science', 'AB Political Science'), ('AB English Studies', 'AB English Studies'), ('AB History', 'AB History'), ('BS Biology', 'BS Biology'), ('BS Chemistry', 'BS Chemistry'), ('BS Mathematics', 'BS Mathematics'), ('BSEd English', 'BSEd English'), ('BSEd Mathematics', 'BSEd Mathematics'), ('BSEd Science', 'BSEd Science'), ('BS Early Childhood Education', 'BS Early Childhood Education'), ('BS Nursing', 'BS Nursing'), ('BS Architecture', 'BS Architecture'), ('BS Interior Design', 'BS Interior Design'), ('BS Fine Arts (major in Painting, Sculpture, or Multimedia Arts)', 'BS Fine Arts'), ('BS Agriculture', 'BS Agriculture'), ('BS Agricultural Engineering', 'BS Agricultural Engineering'), ('BS Forestry', 'BS Forestry'), ('Bachelor of Laws (LLB)', 'Bachelor of Laws (LLB)'), ('Juris Doctor (JD)', 'Juris Doctor (JD)'), ('Doctor of Medicine (MD)', 'Doctor of Medicine (MD)'), ('BS Medical Technology', 'BS Medical Technology'), ('BS Radiologic Technology', 'BS Radiologic Technology'), ('BS Physical Therapy', 'BS Physical Therapy'), ('BS Occupational Therapy', 'BS Occupational Therapy'), ('BS Hospitality Management', 'BS Hospitality Management'), ('BS Tourism Management', 'BS Tourism Management'), ('BS Criminology', 'BS Criminology'), ('BS Social Work', 'BS Social Work')], default='BS Civil Engineering', max_length=120, verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest_set', to='core.department'),
        ),
        migrations.AlterField(
            model_name='newenrollee',
            name='course',
            field=models.CharField(choices=[('BS Civil Engineering', 'BS Civil Engineering'), ('BS Mechanical Engineering', 'BS Mechanical Engineering'), ('BS Electrical Engineering', 'BS Electrical Engineering'), ('BS Electronics and Communications Engineering', 'BS Electronics and Communications Engineering'), ('BS Chemical Engineering', 'BS Chemical Engineering'), ('BS Computer Science', 'BS Computer Science'), ('BS Information Technology', 'BS Information Technology'), ('BS Information Systems', 'BS Information Systems'), ('BS Software Engineering', 'BS Software Engineering'), ('BS Business Administration (Major in Marketing Management)', 'BS Business Administration (Marketing Management)'), ('BS Business Administration (Major in Financial Management)', 'BS Business Administration (Financial Management)'), ('BS Accountancy', 'BS Accountancy'), ('BS Entrepreneurship', 'BS Entrepreneurship'), ('BS Management Accounting', 'BS Management Accounting'), ('AB Psychology', 'AB Psychology'), ('AB Political Science', 'AB Political Science'), ('AB English Studies', 'AB English Studies'), ('AB History', 'AB History'), ('BS Biology', 'BS Biology'), ('BS Chemistry', 'BS Chemistry'), ('BS Mathematics', 'BS Mathematics'), ('BSEd English', 'BSEd English'), ('BSEd Mathematics', 'BSEd Mathematics'), ('BSEd Science', 'BSEd Science'), ('BS Early Childhood Education', 'BS Early Childhood Education'), ('BS Nursing', 'BS Nursing'), ('BS Architecture', 'BS Architecture'), ('BS Interior Design', 'BS Interior Design'), ('BS Fine Arts (major in Painting, Sculpture, or Multimedia Arts)', 'BS Fine Arts'), ('BS Agriculture', 'BS Agriculture'), ('BS Agricultural Engineering', 'BS Agricultural Engineering'), ('BS Forestry', 'BS Forestry'), ('Bachelor of Laws (LLB)', 'Bachelor of Laws (LLB)'), ('Juris Doctor (JD)', 'Juris Doctor (JD)'), ('Doctor of Medicine (MD)', 'Doctor of Medicine (MD)'), ('BS Medical Technology', 'BS Medical Technology'), ('BS Radiologic Technology', 'BS Radiologic Technology'), ('BS Physical Therapy', 'BS Physical Therapy'), ('BS Occupational Therapy', 'BS Occupational Therapy'), ('BS Hospitality Management', 'BS Hospitality Management'), ('BS Tourism Management', 'BS Tourism Management'), ('BS Criminology', 'BS Criminology'), ('BS Social Work', 'BS Social Work')], default='BS Civil Engineering', max_length=120, verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='newenrollee',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_enrollee_set', to='core.department'),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_set', to='core.department'),
        ),
        migrations.AlterField(
            model_name='transactionnf1',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nf1_transactions', to='core.course'),
        ),
        migrations.AlterField(
            model_name='transactionnf1',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nf1_transactions', to='core.department'),
        ),
        migrations.AlterField(
            model_name='transactionnf1',
            name='guest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nf1_transactions', to='core.guest'),
        ),
        migrations.AlterField(
            model_name='transactionnf1',
            name='new_enrollee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nf1_transactions', to='core.newenrollee'),
        ),
        migrations.AlterField(
            model_name='transactionnf1',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nf1_transactions', to='core.student'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$Mbhov67eQ5wI0og7CUmzDy$1ORs92y+lhsAOgSKXjbm+HP5/Q3LN92JhoPmdqBfqZU=', max_length=128, verbose_name='Password'),
        ),
    ]
