# Generated by Django 5.2 on 2025-05-05 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_transaction_requester_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$Aooc63J9HLigXMJW6VPawx$V9u3O9KtUj3c+/+sj2keonqkGQmimOkzFR7XGzwKBzA=', max_length=128, verbose_name='Password'),
        ),
    ]
