# Generated by Django 5.2 on 2025-05-06 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='department',
        ),
        migrations.RemoveField(
            model_name='newenrollee',
            name='department',
        ),
        migrations.RemoveField(
            model_name='student',
            name='department',
        ),
        migrations.RemoveField(
            model_name='transactionnf1',
            name='department',
        ),
        migrations.AlterField(
            model_name='guest',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest_set', to='core.course'),
        ),
        migrations.AlterField(
            model_name='newenrollee',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_enrollee_set', to='core.course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_set', to='core.course'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$dlmwS1nutqs1gphzrGEHDy$kpH8OgoP1OmEP1XqNu7pvyrVHhvfcJO7N1NC7EiTEcQ=', max_length=128, verbose_name='Password'),
        ),
    ]
