# Generated by Django 5.2 on 2025-05-07 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_guest_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='priority',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$0xEBQJE0hG89LKh3eoyBkm$LLsEipljhAmNdwmTVZLBV5AK3X0UJfKQk1DS7fl1PcY=', max_length=128, verbose_name='Password'),
        ),
    ]
