# Generated by Django 5.2 on 2025-05-07 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_student_priority_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionnf1',
            name='queueNumber',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$3xMsU2Cn4ql8dpbMf9Mpsl$mgwSBKlb2uV2FTbop/7sXPWrRHEzeoLFjpA5n8zcXJc=', max_length=128, verbose_name='Password'),
        ),
    ]
