# Generated by Django 5.2 on 2025-05-07 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_transactionnf1_queuenumber_alter_user_password'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='transactionnf1',
            name='unique_queue_number',
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$1PDrsyiYL8Szug79Gml2j0$0VMuuYJ9nhgQqricWqPLnWQE1u4w0vPY20mSdwizZBM=', max_length=128, verbose_name='Password'),
        ),
    ]
