# Generated by Django 5.2 on 2025-05-07 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_remove_transactionnf1_unique_queue_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$JuSbPk9zS6XFIb60gFMGXo$ziY6g+P6n/yWshh7rPKeG1KbXFJ0WbLM85+nxEa4Ozo=', max_length=128, verbose_name='Password'),
        ),
    ]
