# Generated by Django 5.2 on 2025-05-07 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$OjdC85NufFTT4cEy0uzNxy$eoXD/VIlYKhXwX2x0+4l4OQHGpRzGmSQLliRkWRj7Pc=', max_length=128, verbose_name='Password'),
        ),
    ]
