# Generated by Django 5.2 on 2025-05-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$hLX0uObG6keomYzYOMhL3D$y4BPqnho1kxRekkm+IUBZIT1UBT9kH+07IuMF78YFzM=', max_length=128, verbose_name='Password'),
        ),
    ]
