# Generated by Django 5.2 on 2025-05-07 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$RbsnqsHw73VICBzLGm41AI$xctGqIffG4MywM7yi+YpEYiRe5Nx0PKGyz2+ySoE5Wo=', max_length=128, verbose_name='Password'),
        ),
    ]
