# Generated by Django 5.2 on 2025-05-07 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$1000000$VnPvZS6z85FzcvbeydPTFL$of58pu67RGOVUgq/Ske1bT6V+3UNCoh9gczGSEt0Agc=', max_length=128, verbose_name='Password'),
        ),
    ]
