# Generated by Django 5.0.14 on 2025-05-07 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$0wWA08hfzdFijxfVwPXZIj$SjnXCMrNTc9HxQRqYbJhVlz0XlPw9rHNLveQHUunPEQ=', max_length=128, verbose_name='Password'),
        ),
    ]
