# Generated by Django 5.0.14 on 2025-05-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$E7yCHff4uJrvNIiByMhdhX$F3fQkLhjb5grcBxoO+qAX1DTfUQ5EdO4zxmaGH2e2k4=', max_length=128, verbose_name='Password'),
        ),
    ]
