# Generated by Django 5.0.14 on 2025-05-08 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$Xs1kSGgmY9ZToYSowSSPDg$9IaxldphXeH7jn9xUOf/P8Z6/ocINvM6RGGByzTfYz4=', max_length=128, verbose_name='Password'),
        ),
    ]
