# Generated by Django 5.0.14 on 2025-05-08 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$q3JMTwN5g4c70CB4IJG5eY$SPsAL0dkydDgQ0y4B9XTaCQxKpt1+K0NW95Sj+wouJE=', max_length=128, verbose_name='Password'),
        ),
    ]
