# Generated by Django 5.0.14 on 2025-05-08 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$KocHB0fxaMTnNQ0Eqq22dc$Q0Oi0rsOi9s8kV5Klfvzj+Pi2hpSZnRfR27Aj61X8VI=', max_length=128, verbose_name='Password'),
        ),
    ]
