# Generated by Django 5.0.14 on 2025-05-08 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$h6irrmAZxI7n0nfFoXq1bp$CuAz7QWMBgxRGsCB1+qIoTdbd1BxImY8zk1iWl+5pgo=', max_length=128, verbose_name='Password'),
        ),
    ]
