# Generated by Django 5.0.14 on 2025-05-08 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$JK7gFuXubxPswWMfWJTrWK$9ZlJJ6Kgn4uRCkN0bKe+y7ZznpLV8Z+08SG4qTX12sM=', max_length=128, verbose_name='Password'),
        ),
    ]
