# Generated by Django 5.0.14 on 2025-05-08 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$a81VpnAkUS6o21i8Def8Q3$ATPJX8MNtU5eYBl1tfckpPBvAHetYFnQdg7aEmh0vcU=', max_length=128, verbose_name='Password'),
        ),
    ]
