# Generated by Django 5.0.14 on 2025-05-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$9CCkxbJBQMC9ZlNY02ir4b$BJioSNwOkuGeRI929d324p15SfhKVfzfxmF+mXM5cmA=', max_length=128, verbose_name='Password'),
        ),
    ]
