# Generated by Django 5.0.14 on 2025-05-13 18:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='CutoffSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus', models.CharField(blank=True, choices=[('Main', 'Main'), ('South', 'South'), ('San Jose', 'San Jose')], max_length=100, null=True)),
                ('is_cutoff', models.BooleanField(default=False)),
                ('cutoff_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-cutoff_time'],
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$bNMMg62g4aP8KtPieDwL3A$+foV1W5hxo3udLHUmrtYeyi4DLPDn5MjzHCuuJ9JGQY=', max_length=128, verbose_name='Password'),
        ),
    ]
