# Generated by Django 5.0.14 on 2025-05-13 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_cutoffschedule_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$drS4an9bcDRwMHAksGT91b$tkvBPV79dK+orVIvtL7gU/bLbLSYd2w/MUEuzlF0U1g=', max_length=128, verbose_name='Password'),
        ),
    ]
