# Generated by Django 5.0.14 on 2025-05-13 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$ZgFDgDifOLZgWKb0r0m2hd$3mUSZAqY8z9LnjB00QHicMdI6HGjvdXiasYE0dw0uTA=', max_length=128, verbose_name='Password'),
        ),
    ]
