# Generated by Django 5.0.14 on 2025-05-13 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$JUQRXU5TxDHkSu8tqGOVii$aCs1E/lY+pz2NYl1801HoIWPSZZO4FrelkUv2496A2g=', max_length=128, verbose_name='Password'),
        ),
    ]
