# Generated by Django 5.0.14 on 2025-05-13 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$4E7dWeFM4cEUkgkm66hEFi$UH+y2uL+S8+6km/qzsDfK+uhpDSrW2WnmqpuuKbX6kE=', max_length=128, verbose_name='Password'),
        ),
    ]
