# Generated by Django 5.0.14 on 2025-05-13 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$C48om58vj4FNNO9XtpNs2L$EpWxcKt+oIhwnBIqXh3sXapCeNKeds+FsVFdtFv63aE=', max_length=128, verbose_name='Password'),
        ),
    ]
