# Generated by Django 5.0.14 on 2025-05-13 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$mnwdd1RoTsPm80NAY2rFbl$dzYdXZjuY2v/WADSlLWRz8rMM4npnfijxHQ7vLY+GaI=', max_length=128, verbose_name='Password'),
        ),
    ]
