# Generated by Django 5.0.14 on 2025-05-14 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$KyDnFo5ZV0nmy6zJNEM70j$6pP4BU5bCTNdalTuj4cSglxmFbBonm0GdOxfTD0zCNY=', max_length=128, verbose_name='Password'),
        ),
    ]
