# Generated by Django 5.0.14 on 2025-05-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$HvuEhCkcX10ugYOvc9g43e$s01ZXl/SP+HM+Xjs10HaIqBEpstfLJuBtTv/6RLrM0o=', max_length=128, verbose_name='Password'),
        ),
    ]
