# Generated by Django 5.0.14 on 2025-05-20 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_alter_transaction_created_at_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$TnQGwijarXDQDLQVbLfMYJ$J9sHHj0ylUVw+6OPM0jIYASEUO7SggmD+3sodXo8/Tg=', max_length=128, verbose_name='Password'),
        ),
    ]
