# Generated by Django 5.0.14 on 2025-05-20 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='year_level',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Year 1'), (2, 'Year 2'), (3, 'Year 3'), (4, 'Year 4'), (5, 'Year 5')], default=1, verbose_name='Year Level'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$VkpOPv2TBYQSQKYMRiQNbF$f+atiV/9weFTvsNOlNZvYjfztiS+WhwuPfDfu0kV5Vw=', max_length=128, verbose_name='Password'),
        ),
    ]
