# Generated by Django 5.0.14 on 2025-05-20 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_student_year_level_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='priority_request',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$qntj7YvS0VTPQWqe9PFauY$jbvIqVoGK0z/tXJ5jVwA1dcikGwfFS62T20Kl0g3efs=', max_length=128, verbose_name='Password'),
        ),
    ]
