# Generated by Django 5.0.14 on 2025-05-20 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_student_priority_request_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_for',
            field=models.CharField(choices=[('sem_1', 'Sem 1'), ('sem_2', 'Sem 2'), ('summer', 'Summer'), ('off_term', 'Off Term')], default='sem_1', max_length=20),
        ),
        migrations.AddField(
            model_name='transactionnf1',
            name='transaction_for',
            field=models.CharField(choices=[('sem_1', 'Sem 1'), ('sem_2', 'Sem 2'), ('summer', 'Summer'), ('off_term', 'Off Term')], default='sem_1', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$cD6fqnQjaqbFmlCPmuPbrv$I9VqRhYVT1N0fc8iYYVfSjQMHBTuRfmpYPFzEXVF6r4=', max_length=128, verbose_name='Password'),
        ),
    ]
