# Generated by Django 5.0.14 on 2025-05-20 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_transaction_transaction_for_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionnf1',
            name='transaction_for',
            field=models.CharField(choices=[('enrollment', 'Enrollment'), ('sem_1', 'Sem 1'), ('sem_2', 'Sem 2'), ('summer', 'Summer'), ('off_term', 'Off Term')], default='sem_1', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$OtdilP0NCk0fNsKNDDodO4$WDibML2cq9l9VWroLemyTVVnHe6EnwSmKyd6qQCx7mU=', max_length=128, verbose_name='Password'),
        ),
    ]
