# Generated by Django 5.0.14 on 2025-05-20 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_alter_transactionnf1_transaction_for_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$RYFeCEv2aPVnIgydGpxAiZ$SKEmcBU49h0cNQ/koC1MjxWxWWDAdm/2rqrg/IzFA6c=', max_length=128, verbose_name='Password'),
        ),
    ]
