# Generated by Django 5.0.14 on 2025-05-20 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$dX9yZOMIlcVaBI3rI9obVV$t80eeMOvWuI5ZiZqM6AOxUfKTOZM6ZGQZbESF9uMa9k=', max_length=128, verbose_name='Password'),
        ),
    ]
