# Generated by Django 5.0.14 on 2025-05-20 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$LWC1z7u5wqhbgQwuXVwS47$Benu6LIHRyLKRPOVExa5ZlabiTjyRwQ434PN6qEckw8=', max_length=128, verbose_name='Password'),
        ),
    ]
