# Generated by Django 5.0.14 on 2025-05-21 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$CMib4knSTr01aIkqlDzGTI$m1OF74LgG1/K5o7Oi6OUMj2FXI58lnPgYFRVBnGWSoM=', max_length=128, verbose_name='Password'),
        ),
    ]
