# Generated by Django 5.0.14 on 2025-05-26 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$xojcQokY6Amu1z2tXnOPBW$D7THL9YePx/JCZSjPp4b0lNZCGzXd5Xus+IB0habaYw=', max_length=128, verbose_name='Password'),
        ),
    ]
