# Generated by Django 5.0.14 on 2025-05-26 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$LDPABZ2EEkDEh51tOUuJhP$yHFvREeFiwr09NZkj6nQAmk4JokEgQ+2xxVSRAG/Z0A=', max_length=128, verbose_name='Password'),
        ),
    ]
