# Generated by Django 5.0.14 on 2025-05-26 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$N7GCnmHcfxCZPxvfPhge57$xROhbvryMawoK+51FLxSx518Z180XaPBzbY2Zcc+Ers=', max_length=128, verbose_name='Password'),
        ),
    ]
