# Generated by Django 5.0.14 on 2025-08-03 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$kT97ZEA7DywiaDZa6M5EFg$Bh7CyBTyY/0aTB99k4NfAQfJuu5PD6M0VdHQQJO1BGU=', max_length=128, verbose_name='Password'),
        ),
    ]
