# Generated by Django 5.0.14 on 2025-08-07 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_alter_user_password_twofactortoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='twofactortoken',
            name='code',
            field=models.CharField(default=123456, max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$thCoY9jGxfnYmqEWXHHz1F$jTVCxVJkFSEaweAB/ikjX+Un5kF/yefjKkQCuy6+w/c=', max_length=128, verbose_name='Password'),
        ),
    ]
