# Generated by Django 5.0.14 on 2025-08-07 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_twofactortoken_code_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$MGlWwJ3jj0Wp1EzMnBYBgC$r54mQ0NvM5Uh8TVbDs2bsp6p7D8QqrqZVgE6qlUdTA0=', max_length=128, verbose_name='Password'),
        ),
    ]
