# Generated by Django 5.0.14 on 2025-08-14 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$8le45QXt1yhM4ZaZtgq811$Bu0rEP46bQcSRnQx1b1hiZIe0aroMvDp+dpUWCCRbAA=', max_length=128, verbose_name='Password'),
        ),
    ]
