# Generated by Django 5.0.14 on 2025-08-27 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='studentId',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$z5fSVKk7bVDHSKs76p0Upu$HVlmeaW7SESOKa78LgiXKOYzI9N2OQUQq/mjA7pfUq8=', max_length=128, verbose_name='Password'),
        ),
    ]
