# Generated by Django 5.0.14 on 2025-08-27 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_alter_student_studentid_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='studentId',
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$UErD2xTg5C0soMhsACTnWe$gVniLvgF4lr4qN5iN4J8+twSXFDU0vbUJHeaBvebvqI=', max_length=128, verbose_name='Password'),
        ),
    ]
