# Generated by Django 5.0.14 on 2025-10-07 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_alter_student_studentid_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$Bpq2tPQn11sNX3tkCX8mUo$+xoZEvr4CAEGgk6FT8g9wU44ax46AY3DiIIdgvK5sVM=', max_length=128, verbose_name='Password'),
        ),
    ]
