# Generated by Django 5.0.14 on 2025-10-07 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$3pwyky0yL6iK4w803Gv4wf$0CgGeMhFDhIABp0/2AzovV2r0NIj55c0DjnrBtgpj4I=', max_length=128, verbose_name='Password'),
        ),
    ]
