# Generated by Django 5.0.14 on 2025-10-07 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$trzcElV192T0n9QGXOmpX9$1Hf99OL78i01mEGiauM35UZ3sLLyLTXqnRfCNGN8daA=', max_length=128, verbose_name='Password'),
        ),
    ]
