# Generated by Django 5.0.14 on 2025-10-07 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$xH3eWjEMBl7nbln7qemHNZ$bc6IqO7LoMicBVFdgGsU6WV/FJJhfJi1WmScM/rshQ4=', max_length=128, verbose_name='Password'),
        ),
    ]
