# Generated by Django 5.0.14 on 2025-10-07 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$OzHdze2PtrBWrfzRVjIduY$p16bxhItthCISEduwrzmu0jX6yZAxQ5W/gGBW+FOzXQ=', max_length=128, verbose_name='Password'),
        ),
    ]
