# Generated by Django 5.0.14 on 2025-10-08 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$mRofmSngPVdM0Y85iKrs54$pdKDoBAeW2GcpgEICd59TydE3Ae8YqXvqMHZqHGZBCM=', max_length=128, verbose_name='Password'),
        ),
    ]
