# Generated by Django 5.0.14 on 2025-10-08 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$s466ue0N76lt5lA7ynbjsi$d+O6Tal691I5lSbN3zbbI39jP+uv2f/AiBEDiPyX7Fw=', max_length=128, verbose_name='Password'),
        ),
    ]
