# Generated by Django 5.0.14 on 2025-10-08 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$iPWgHlKjQ73jgF7ZpnERlr$qLRmcS4bU8WDLIWLBMiZZzPMCIEkoEbR8LJTClZHm4k=', max_length=128, verbose_name='Password'),
        ),
    ]
